#include "TorchDrumLib.h"

#include "Biquad.cpp"
#include "FeatureExtraction/FeatureExtraction.cpp"
#include "OnsetDetection.cpp"
#include "Synth/DrumSynth.cpp"
#include "Synth/Modules/Envelope.cpp"
#include "Synth/Modules/ExpDecayEnvelope.cpp"
#include "Synth/Modules/SinusoidalOscillator.cpp"
#include "Synth/Modules/Tonal.cpp"
#include "SynthController.cpp"
#include "Utils/NeuralNetworkMock.cpp"
